from barbarianTabController import BarbarianTabController
from bardTabController      import BardTabController
from clericTabController    import ClericTabController
from druidTabController     import DruidTabController
from fighterTabController   import FighterTabController
from monkTabController      import MonkTabController
from paladinTabController   import PaladinTabController
from rangerTabController    import RangerTabController
from rogueTabController     import RogueTabController
from sorcererTabController  import SorcererTabController
from wizardTabController    import WizardTabController